# .streamlit/config.toml

[theme]
base = "light"
primaryColor = "#1E88E5"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F8F9FA"
textColor = "#212121"
font = "sans serif"

[server]
enableCORS = true
enableXsrfProtection = true 